# Generated by Django 5.0.6 on 2024-05-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_curriculum_instructor_alter_course_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("EXPERT", "Expert"),
                ],
                max_length=20,
            ),
        ),
    ]
