# Generated by Django 5.0.6 on 2024-05-13 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_curriculum_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculums",
                to="api.course",
            ),
        ),
    ]
