# Generated by Django 5.0.6 on 2024-05-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_lesson_curriculum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(),
        ),
    ]
