# Generated by Django 5.0.6 on 2024-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_lesson_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image1",
            field=models.ImageField(default="image.png", upload_to="post_images"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="image2",
            field=models.ImageField(default="image.png", upload_to="post_images"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="image3",
            field=models.ImageField(default="image.png", upload_to="post_images"),
            preserve_default=False,
        ),
    ]
