# Generated by Django 5.0.6 on 2024-05-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_student_courses_enlisted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="courses_enlisted",
            field=models.ManyToManyField(to="api.course"),
        ),
    ]
