# Generated by Django 5.0.6 on 2024-05-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_student_courses_enlisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("EXPERT", "Expert"),
                ],
                default="Beginner",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(default="4 Weeks", max_length=100),
            preserve_default=False,
        ),
    ]
