# Generated by Django 5.0.6 on 2024-05-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_instructor_courses_taught"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="duration",
            field=models.CharField(default="20 Minutes", max_length=100),
            preserve_default=False,
        ),
    ]
