# Generated by Django 5.0.6 on 2024-05-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_payment_duration_months_payment_subscription_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="description",
            field=models.TextField(),
        ),
    ]
