# Generated by Django 5.0.6 on 2024-06-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
