# Generated by Django 5.0.6 on 2024-06-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_blob",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
